// regen-decisions-index.test.mjs — verifies the deterministic Standing Decisions generator.
// Builds throwaway repos under tmpdir with known decision files and asserts the rendered block,
// insert/replace/remove behavior, status filtering, and the --check exit code. Prints "OK".
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { extractBlock, readDecisions, renderBlock, writeBlock } from "./regen-decisions-index.mjs";

const SCRIPT = join(dirname(fileURLToPath(import.meta.url)), "regen-decisions-index.mjs");

function makeRepo() {
	const repo = mkdtempSync(join(tmpdir(), "decisions-"));
	mkdirSync(join(repo, ".rpiv", "decisions"), { recursive: true });
	return repo;
}
function decision(repo, key, { status = "accepted", rule = `rule for ${key}` } = {}) {
	writeFileSync(
		join(repo, ".rpiv", "decisions", `${key}.md`),
		`---\nkey: ${key}\nstatus: ${status}\nrule: "${rule}"\n---\n\n# ${key}\n`,
	);
}
const CLAUDE = (body) => `# Project\n\n${body}\n`;

let repo;
try {
	// --- render: accepted decisions sorted by key, rule + link per line, retired excluded ---
	repo = makeRepo();
	decision(repo, "zeta", { rule: "z rule" });
	decision(repo, "alpha", { rule: "a rule" });
	decision(repo, "old", { status: "retired", rule: "should not appear" });
	const block = renderBlock(readDecisions(repo));
	assert.ok(block.includes("## Standing Decisions"), "block has the section header");
	assert.ok(
		block.indexOf("**alpha**") < block.indexOf("**zeta**"),
		"decisions are sorted by key (alpha before zeta)",
	);
	assert.ok(block.includes("- **alpha** — a rule [.rpiv/decisions/alpha.md]"), "renders rule + link");
	assert.ok(!block.includes("retired") && !block.includes("should not appear"), "retired is excluded");
	rmSync(repo, { recursive: true, force: true });

	// --- insert-if-absent: block appended, prior content preserved ---
	repo = makeRepo();
	decision(repo, "alpha");
	writeFileSync(join(repo, "CLAUDE.md"), CLAUDE("Original body line."));
	assert.equal(writeBlock(repo), true, "writeBlock reports a change on first insert");
	let md = readFileSync(join(repo, "CLAUDE.md"), "utf-8");
	assert.ok(md.includes("Original body line."), "existing CLAUDE.md content is preserved");
	assert.ok(md.includes("**alpha**"), "block was inserted");
	assert.equal(writeBlock(repo), false, "second write is a no-op (idempotent)");
	rmSync(repo, { recursive: true, force: true });

	// --- replace-in-place: a stale block is replaced, surrounding content kept ---
	repo = makeRepo();
	decision(repo, "alpha", { rule: "fresh rule" });
	const staleBlock =
		"<!-- BEGIN standing-decisions (generated by regen-decisions-index.mjs — do not edit inside) -->\n" +
		"## Standing Decisions\n\nstale contents\n" +
		"<!-- END standing-decisions -->";
	writeFileSync(join(repo, "CLAUDE.md"), CLAUDE(`before\n\n${staleBlock}\n\nafter`));
	writeBlock(repo);
	md = readFileSync(join(repo, "CLAUDE.md"), "utf-8");
	assert.ok(md.includes("before") && md.includes("after"), "content around the block is preserved");
	assert.ok(md.includes("fresh rule") && !md.includes("stale contents"), "block content was refreshed");
	assert.equal((md.match(/BEGIN standing-decisions/g) ?? []).length, 1, "exactly one block (no duplication)");
	rmSync(repo, { recursive: true, force: true });

	// --- empty decisions: an existing block is removed; --check passes with no block ---
	repo = makeRepo();
	writeFileSync(join(repo, "CLAUDE.md"), CLAUDE(`keep\n\n${staleBlock}\n\nkeep2`));
	writeBlock(repo); // no decision files => desired == "" => region removed
	md = readFileSync(join(repo, "CLAUDE.md"), "utf-8");
	assert.ok(!md.includes("BEGIN standing-decisions"), "block removed when there are no decisions");
	assert.ok(md.includes("keep") && md.includes("keep2"), "surrounding content survives removal");
	assert.equal(extractBlock(md), "", "extractBlock returns empty when absent");
	rmSync(repo, { recursive: true, force: true });

	// --- --check exit codes via the CLI ---
	repo = makeRepo();
	decision(repo, "alpha", { rule: "v1" });
	writeFileSync(join(repo, "CLAUDE.md"), CLAUDE("body"));
	execFileSync("node", [SCRIPT, repo], { encoding: "utf-8" }); // write the block
	execFileSync("node", [SCRIPT, "--check", repo], { encoding: "utf-8" }); // in sync -> exit 0
	decision(repo, "alpha", { rule: "v2-changed" }); // drift the source
	assert.throws(
		() => execFileSync("node", [SCRIPT, "--check", repo], { stdio: "pipe" }),
		/STALE/,
		"--check exits nonzero and reports STALE when CLAUDE.md drifts from the decision files",
	);
	rmSync(repo, { recursive: true, force: true });

	console.log("OK (regen-decisions-index) — render, insert, replace, remove, status filter, --check gate.");
} catch (err) {
	if (repo) rmSync(repo, { recursive: true, force: true });
	throw err;
}
