// layer-rules.test.mjs — layer-model -> dependency-cruiser config synthesis: rule shape,
// direction convention (deep must not import shallow), --forbid boundaries, regex
// escaping, CJS loadability, degradation. No dependencies; prints "OK" on success.
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { mkdtempSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const L = join(dirname(fileURLToPath(import.meta.url)), "layer-rules.mjs");
const tmp = mkdtempSync(join(tmpdir(), "layer-rules-"));
const require_ = createRequire(import.meta.url);
let seq = 0;

const write = (name, content) => {
	const p = join(tmp, `${seq += 1}-${name}`);
	writeFileSync(p, typeof content === "string" ? content : JSON.stringify(content));
	return p;
};
const run = (args) => execFileSync("node", [L, ...args], { encoding: "utf-8" });

const LAYERS = [
	{ name: "Layer 0 — public surface", paths: ["src/app"] },
	{ name: "Layer 1 — services", paths: ["src/svc", "src/util"] },
	{ name: "Layer 2 — domain", paths: ["src/domain"] },
];

// ── Case 1: JSON rules — one no-upward rule per deep layer + no-circular ─────
{
	const layers = write("layers.json", LAYERS);
	const { forbidden } = JSON.parse(run([`--layers=${layers}`, "--format=json"]));
	assert.deepEqual(forbidden.map((r) => r.name), ["no-upward-l1", "no-upward-l2", "no-circular"]);

	const l1 = forbidden[0];
	assert.equal(l1.from.path, "^(src/svc|src/util)/", "L1 from: both same-layer paths");
	assert.equal(l1.to.path, "^(src/app)/", "L1 to: only shallower layers");
	assert.equal(l1.severity, "error");

	const l2 = forbidden[1];
	assert.equal(l2.from.path, "^(src/domain)/");
	assert.equal(l2.to.path, "^(src/app|src/svc|src/util)/", "L2 banned from ALL shallower layers");
	assert.match(l2.comment, /Layer 2 — domain must not import Layer 0 — public surface \/ Layer 1 — services/);

	assert.deepEqual(forbidden[2], {
		name: "no-circular",
		severity: "error",
		comment: "cycles are direction violations by definition",
		from: {},
		to: { circular: true },
	});
}

// ── Case 2: --forbid boundary pairs (repeatable) land between layers rules and no-circular ──
{
	const layers = write("layers.json", LAYERS);
	const { forbidden } = JSON.parse(run([
		`--layers=${layers}`, "--format=json",
		"--forbid=src/domain->src/infra", "--forbid=src/billing->src/gym",
	]));
	assert.deepEqual(forbidden.map((r) => r.name),
		["no-upward-l1", "no-upward-l2", "boundary-1", "boundary-2", "no-circular"]);
	assert.equal(forbidden[2].from.path, "^(src/domain)/");
	assert.equal(forbidden[2].to.path, "^(src/infra)/");
	assert.match(forbidden[2].comment, /System Model/);
}

// ── Case 3: forbid-only mode (no layer file) still emits boundaries + no-circular ──
{
	const { forbidden } = JSON.parse(run(["--format=json", "--forbid=a->b"]));
	assert.deepEqual(forbidden.map((r) => r.name), ["boundary-1", "no-circular"]);
}

// ── Case 4: regex escaping + trailing-slash normalization ────────────────────
{
	const layers = write("layers.json", [
		{ name: "L0", paths: ["src/v1.2/"] },
		{ name: "L1", paths: ["src/core+util"] },
	]);
	const { forbidden } = JSON.parse(run([`--layers=${layers}`, "--format=json"]));
	assert.equal(forbidden[0].from.path, "^(src/core\\+util)/", "+ escaped");
	assert.equal(forbidden[0].to.path, "^(src/v1\\.2)/", "dot escaped, trailing slash normalized");
}

// ── Case 5: default CJS output is loadable and structurally complete ─────────
{
	const layers = write("layers.json", LAYERS);
	const cjs = run([`--layers=${layers}`]);
	assert.match(cjs, /^\/\/ \.dependency-cruiser\.cjs — GENERATED by rpiv architectural-review/);
	assert.match(cjs, /L1: Layer 1 — services — src\/svc, src\/util/, "header documents the layer order");
	const p = join(tmp, `${seq += 1}-gen.cjs`);
	writeFileSync(p, cjs);
	const cfg = require_(p);
	assert.equal(cfg.forbidden.length, 3);
	assert.equal(cfg.options.doNotFollow.path, "node_modules");
	assert.match("src/api/user.test.ts", new RegExp(cfg.options.exclude.path), "test files excluded");
	assert.doesNotMatch("src/api/user.ts", new RegExp(cfg.options.exclude.path), "source files kept");
	for (const r of cfg.forbidden) {
		if (r.from.path) new RegExp(r.from.path); // must compile
		if (r.to.path) new RegExp(r.to.path);
	}
	assert.match("src/domain/model.ts", new RegExp(cfg.forbidden[1].from.path), "deep layer matches its own rule");
	assert.doesNotMatch("src/domainx/model.ts", new RegExp(cfg.forbidden[1].from.path), "prefix does not bleed past the dir boundary");
}

// ── Case 6: degradation — note + exit 0, never throws ────────────────────────
{
	assert.match(run(["--layers=" + join(tmp, "nope.json")]), /^note: layers file unreadable/);
	const bad = write("bad.json", "{not json");
	assert.match(run([`--layers=${bad}`]), /^note: layers file is not valid JSON/);
	const one = write("one.json", [{ name: "L0", paths: ["src"] }]);
	assert.match(run([`--layers=${one}`]), /^note: need >= 2 layers/);
	const malformed = write("malformed.json", [{ name: "L0", paths: [] }, { name: "L1", paths: ["b"] }]);
	assert.match(run([`--layers=${malformed}`]), /^note: layer 0 malformed/);
	assert.match(run([`--forbid=oops`]), /^note: --forbid 0 malformed/);
}

console.log("OK (layer-rules) — per-layer no-upward rules + boundary pairs + escaping + loadable CJS + degradation.");
